CREATE TABLE workflow_runs (
 id VARCHAR(36) PRIMARY KEY, scenario VARCHAR(32) NOT NULL, requirement CLOB NOT NULL,
 state VARCHAR(32) NOT NULL, revision INT NOT NULL, version BIGINT NOT NULL,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
 active_ms BIGINT NOT NULL DEFAULT 0, repair_count INT NOT NULL DEFAULT 0,
 baseline VARCHAR(2048) NOT NULL, baseline_hash VARCHAR(64) NOT NULL, reason VARCHAR(2048)
);
CREATE TABLE workflow_tasks (
 run_id VARCHAR(36) NOT NULL REFERENCES workflow_runs(id), revision INT NOT NULL,
 task_id VARCHAR(64) NOT NULL, definition CLOB NOT NULL, state VARCHAR(32) NOT NULL,
 attempts INT NOT NULL DEFAULT 0, fence BIGINT NOT NULL DEFAULT 0,
 lease_until TIMESTAMP WITH TIME ZONE, retry_after TIMESTAMP WITH TIME ZONE, skill_hash VARCHAR(64), evidence_path VARCHAR(2048), evidence_hash VARCHAR(64),
 candidate_path VARCHAR(2048), candidate_hash VARCHAR(64), input_hash VARCHAR(64),
 PRIMARY KEY(run_id,revision,task_id)
);
CREATE TABLE workflow_attempts (
 id VARCHAR(36) PRIMARY KEY, run_id VARCHAR(36) NOT NULL REFERENCES workflow_runs(id),
 revision INT NOT NULL, task_id VARCHAR(64) NOT NULL, fence BIGINT NOT NULL,
 invocation_id VARCHAR(36) NOT NULL, input_hash VARCHAR(64) NOT NULL,
 workspace VARCHAR(2048) NOT NULL, state VARCHAR(32) NOT NULL,
 started_at TIMESTAMP WITH TIME ZONE NOT NULL, deadline TIMESTAMP WITH TIME ZONE NOT NULL,
 ended_at TIMESTAMP WITH TIME ZONE, pid BIGINT, process_start TIMESTAMP WITH TIME ZONE,
 exit_code INT, input_tokens BIGINT, cached_input_tokens BIGINT, output_tokens BIGINT, evidence_path VARCHAR(2048), evidence_hash VARCHAR(64), detail VARCHAR(2048)
);
CREATE TABLE workflow_events (
 sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 run_id VARCHAR(36) NOT NULL REFERENCES workflow_runs(id), revision INT NOT NULL,
 task_id VARCHAR(64), event_type VARCHAR(64) NOT NULL, detail CLOB NOT NULL,
 occurred_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE workflow_approvals (
 id VARCHAR(36) PRIMARY KEY, run_id VARCHAR(36) NOT NULL REFERENCES workflow_runs(id),
 revision INT NOT NULL, task_id VARCHAR(64) NOT NULL, run_version BIGINT NOT NULL,
 evidence_hash VARCHAR(64) NOT NULL, approved BOOLEAN NOT NULL,
 principal VARCHAR(128) NOT NULL, rationale VARCHAR(2048) NOT NULL,
 occurred_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX workflow_ready ON workflow_tasks(state,run_id,revision);
